version: '3.8'

services:
  flask-app:
    build: ./app
    container_name: flask-app
    environment:
      - FLASK_ENV=development
    volumes:
      - ./app:/app
    ports:
      - '5001:5000'
    depends_on:
      - redis
    command: python -m flask run --host=0.0.0.0

  celery-worker:
    build: ./app
    container_name: celery-worker
    command: celery -A tasks.celery_app worker --loglevel=info
    volumes:
      - ./app:/app
    depends_on:
      - flask-app
      - redis

  celery-beat:
    build: ./app
    container_name: celery-beat
    command: celery -A tasks.celery_app beat --loglevel=info
    volumes:
      - ./app:/app
    depends_on:
      - flask-app
      - redis

  redis:
    image: redis:6.0-alpine
    container_name: redis
    ports:
      - '6379:6379'

  telegram-bot:
    build: ./bot
    container_name: telegram-bot
    environment:
      - TELEGRAM_API_TOKEN=7423810103:AAGKDv7rDV7s-fDXOQgRdp8Ts582oovE5bw
    volumes:
      - ./bot:/bot
    depends_on:
      - flask-app
    command: python bot.py
